trigger:
- master
- dev

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- publish: $(System.DefaultWorkingDirectory)/bin/WebApp
  artifact: WebApp
  
- script: 
    npm install
    npm run build
    npm package
  displayName: 'npm install and build'
